import fs from "node:fs";
const D = {
// ---- 语言 / 语音 ----
"Arabic":"阿拉伯语","Belarusian":"白俄罗斯语","Bengali":"孟加拉语","Bosnian":"波斯尼亚语","Bulgarian":"保加利亚语",
"Catalan":"加泰罗尼亚语","Croatian":"克罗地亚语","Czech":"捷克语","Danish":"丹麦语","Dutch":"荷兰语",
"English":"英语","Estonian":"爱沙尼亚语","Finnish":"芬兰语","Flemish":"弗拉芒语","French":"法语","German":"德语",
"Greek":"希腊语","Hebrew":"希伯来语","Hindi":"印地语","Hungarian":"匈牙利语","Indonesian":"印尼语","Italian":"意大利语",
"Japanese":"日语","Kannada":"卡纳达语","Korean":"韩语","Latvian":"拉脱维亚语","Lithuanian":"立陶宛语",
"Macedonian":"马其顿语","Malay":"马来语","Marathi":"马拉地语","Norwegian":"挪威语","Persian":"波斯语","Polish":"波兰语",
"Portuguese":"葡萄牙语","Romanian":"罗马尼亚语","Russian":"俄语","Serbian":"塞尔维亚语","Slovak":"斯洛伐克语",
"Slovenian":"斯洛文尼亚语","Spanish":"西班牙语","Swedish":"瑞典语","Tagalog":"他加禄语","Tamil":"泰米尔语",
"Telugu":"泰卢固语","Thai":"泰语","Turkish":"土耳其语","Ukrainian":"乌克兰语","Urdu":"乌尔都语","Vietnamese":"越南语",
"Arabic (Algeria)":"阿拉伯语（阿尔及利亚）","Arabic (Chad)":"阿拉伯语（乍得）","Arabic (Egypt)":"阿拉伯语（埃及）",
"Arabic (Iran)":"阿拉伯语（伊朗）","Arabic (Iraq)":"阿拉伯语（伊拉克）","Arabic (Jordan)":"阿拉伯语（约旦）",
"Arabic (Kuwait)":"阿拉伯语（科威特）","Arabic (Lebanon)":"阿拉伯语（黎巴嫩）","Arabic (Morocco)":"阿拉伯语（摩洛哥）",
"Arabic (Palestine)":"阿拉伯语（巴勒斯坦）","Arabic (Qatar)":"阿拉伯语（卡塔尔）","Arabic (Saudi Arabia)":"阿拉伯语（沙特阿拉伯）",
"Arabic (Sudan)":"阿拉伯语（苏丹）","Arabic (Syria)":"阿拉伯语（叙利亚）","Arabic (Tunisia)":"阿拉伯语（突尼斯）",
"Arabic (United Arab Emirates)":"阿拉伯语（阿联酋）","Chinese (Cantonese)":"中文（粤语）","Chinese (Simplified)":"中文（简体）",
"Chinese (Traditional)":"中文（繁体）","Danish (Denmark)":"丹麦语（丹麦）","English (Australia)":"英语（澳大利亚）",
"English (India)":"英语（印度）","English (New Zealand)":"英语（新西兰）","English (United Kingdom)":"英语（英国）",
"English (United States)":"英语（美国）","French (Canada)":"法语（加拿大）","German (Switzerland)":"德语（瑞士）",
"Korean (South Korea)":"韩语（韩国）","Portuguese (Brazil)":"葡萄牙语（巴西）","Portuguese (Portugal)":"葡萄牙语（葡萄牙）",
"Spanish (Latin America)":"西班牙语（拉丁美洲）","Swedish (Sweden)":"瑞典语（瑞典）",
// ---- 通用 UI 标签 ----
"Cancel":"取消","Chat":"聊天","Clear":"清除","Close":"关闭","Collapse":"折叠","Comment":"评论","Confirm":"确认",
"Credits":"积分","Custom":"自定义","Delete":"删除","Description":"描述","Document":"文档","Email":"邮箱",
"Error":"错误","Feedback":"反馈","Hide":"隐藏","Home":"主页","Info":"信息","Input":"输入","Label":"标签",
"Light":"浅色","Loading":"加载中","Message":"消息","Model":"模型","Multilingual":"多语言","Name":"名称",
"Notification":"通知","Off":"关闭","Open":"打开","Patches":"补丁","Patron":"赞助者","Ready":"就绪",
"Reddit":"Reddit","Remove":"移除","Replay":"回放","Report":"报告","Scene":"场景","Schematic":"建筑蓝图",
"Screen":"屏幕","Select":"选择","Server":"服务器","Session":"会话","Share":"分享","Skin":"皮肤","Social":"社交",
"Stream":"流","System":"系统","Text":"文本","Texture":"纹理","Tool":"工具","Unknown":"未知","Unnamed":"未命名",
"Voice":"语音","Volume":"音量","Warn":"警告","Window":"窗口","Home":"主页","Patches":"补丁",
// ---- 应用短语 ----
"Add a screenshot":"添加截图",
"Click and drag to rotate, scroll to zoom.":"按住拖动旋转，滚轮缩放。",
"Click to Copy":"点击复制",
"Copy ID":"复制 ID",
"Delete Character":"删除角色",
"Detail View":"详情视图",
"Edit AI Friend":"编辑 AI 伙伴",
"Edit Character":"编辑角色",
"Guided Tour":"新手引导",
"Minecraft Skin":"Minecraft 皮肤",
"Minutes played":"游玩时长（分钟）",
"No description available":"暂无描述",
"No details available":"暂无详情",
"No error message":"无错误信息",
"No options":"无选项",
"Open Link":"打开链接",
"Open Link Failed":"打开链接失败",
"Play now!":"立即开始！",
"Private AI Friend":"私密 AI 伙伴",
"Remove screenshot":"移除截图",
"Report a Bug":"反馈问题",
"Select AI Friend":"选择 AI 伙伴",
"Selected AI Friend":"已选 AI 伙伴",
"Send Bug Report":"发送问题报告",
"Thank you for your report!":"感谢你的反馈！",
"Unnamed AI Friend":"未命名 AI 伙伴",
"What's the bug? What did you expect?":"遇到了什么问题？你期望的结果是什么？",
"Your Name":"你的名字",
"Unknown error":"未知错误",
"NetworkError when attempting to fetch resource.":"获取资源时发生网络错误。",
"NOTE: Skins work on Player2's servers or in Singleplayer if you have the Skin Restorer mod installed.":"注意：皮肤在 Player2 服务器上生效；单人模式需安装 Skin Restorer 模组。",
"Failed to capture PayPal order":"捕获 PayPal 订单失败",
"Failed to check if user is anonymous":"检查用户匿名状态失败",
"Failed to check login status":"检查登录状态失败",
"Failed to connect chat speech to text":"连接聊天语音识别失败",
"Failed to create PayPal order":"创建 PayPal 订单失败",
"Failed to delete chat message":"删除聊天消息失败",
"Failed to fetch credit daily reward":"获取每日积分奖励失败",
"Failed to fetch credit rewards":"获取积分奖励失败",
"Failed to fetch credits":"获取积分失败",
"Failed to fetch customer portal link":"获取客户门户链接失败",
"Failed to fetch joule receipt filter options":"获取 Joule 收据筛选选项失败",
"Failed to fetch joule receipts":"获取 Joule 收据失败",
"Failed to fetch leaderboard data":"获取排行榜数据失败",
"Failed to fetch more chat history":"获取更多聊天记录失败",
"Failed to fetch patron data":"获取赞助者数据失败",
"Failed to fetch patron deals":"获取赞助者优惠失败",
"Failed to get auth tokens":"获取认证令牌失败",
"Failed to get chat messages":"获取聊天消息失败",
"Failed to get linked identities":"获取已关联身份失败",
"Failed to get user profile":"获取用户资料失败",
"Failed to link identity":"关联身份失败",
"Failed to login":"登录失败",
"Failed to login via website":"通过网站登录失败",
"Failed to purchase patron":"购买赞助者失败",
"Failed to retry sending":"重试发送失败",
"Failed to revise PayPal subscription":"修改 PayPal 订阅失败",
"Failed to send chat message":"发送聊天消息失败",
"Failed to start capture for game mode":"启动游戏画面捕获失败",
"Failed to update chat message":"更新聊天消息失败",
"Failed to update user profile":"更新用户资料失败",
"Failed to upgrade via website":"通过网站升级失败",
"Failed to fetch":"获取失败",
"Load failed":"加载失败"
};
fs.writeFileSync("i18n/zh-CN.json", JSON.stringify(D, null, 2), "utf8");
console.log("dictionary entries:", Object.keys(D).length);