import fs from "node:fs";
const base = JSON.parse(fs.readFileSync("i18n/zh-CN.json","utf8"));
const P = {
"You receive 500J for every purchase they make":"每笔购买你都能获得 500J",
"Your friend gets a 5% discount on their first subscription":"你的好友首次订阅可享 5% 折扣",
"Settings - App configuration":"设置 - 应用配置",
"Daily Power Spin - Free daily energy":"每日能量转盘 - 免费每日能量",
"Plan approved":"计划已通过",
"Play Games - Earn while gaming":"玩游戏 - 边玩边赚",
"Studio - Build AI games":"工作室 - 构建 AI 游戏",
"Home - Your main dashboard":"主页 - 你的主面板",
"AI Power - Your free credits and patron":"AI 能量 - 你的免费积分与赞助",
"Social Media - Follow us for rewards":"社交媒体 - 关注我们领取奖励",
"AI Power Center":"AI 能量中心",
"Connect Account - Link your accounts":"关联账号 - 绑定你的账号",
"Character - Manage your AI companions":"角色 - 管理你的 AI 伙伴",
"Schematics - Building guides":"建筑蓝图 - 建造指南",
"3D Model":"3D 模型","3D Model Provider":"3D 模型提供方",
"A display name for this voice preset":"此语音预设的显示名称",
"A previous install did not finish.":"上次安装未完成。",
"A previous install did not finish. Installing again will complete it.":"上次安装未完成，重新安装即可完成。",
"Accepted formats: .log, .txt (max 10MB)":"支持格式：.log、.txt（最大 10MB）",
"Actions":"操作","Add a new schematic":"添加新蓝图","Add Character":"添加角色",
"Add Custom Inworld Voice ID":"添加自定义 Inworld 语音 ID","Add mapping":"添加映射","Add Schematic":"添加蓝图","Add Voice ID":"添加语音 ID",
"Additional arguments passed to llama.cpp server. Changes apply on next server start.":"传递给 llama.cpp 服务器的额外参数，下次启动服务器时生效。",
"Adjusts playback speed. 1.0x is normal speed.":"调整播放速度，1.0 倍为正常速度。",
"AI Settings":"AI 设置","AISS Setup":"AISS 安装","All":"全部","Already Installed":"已安装","Already Spun Today":"今日已抽过",
"Already-downloaded files are reused, so this usually needs no download at all.":"已下载的文件会被复用，通常无需重新下载。",
"Also available on:":"同时支持：","API Base URL":"API 基础地址",
"Applies to every game and character chat.":"对所有游戏与角色聊天生效。",
"Applies to every image you generate or edit.":"对你生成或编辑的每张图片生效。",
"Approve Plan":"批准计划",
"Are you sure you want to delete this log? This action cannot be undone.":"确定要删除此日志吗？此操作无法撤销。",
"Assign to Character Voice":"分配到角色语音","Assign to Character Voice (optional)":"分配到角色语音（可选）",
"At least 5 seconds of audio is needed when removing background noise":"去除背景噪音至少需要 5 秒音频",
"Audio Files (1-25 files) *":"音频文件（1-25 个）*","Available Now!":"现已可用！","Available rewards":"可用奖励",
"Available to patrons":"仅赞助者可用","Back":"返回","Back to games":"返回游戏","Back to Games":"返回游戏","Back to home":"返回主页",
"Back up a save first, and close Starfield.":"请先备份存档，并关闭《星空》。",
"Backend":"后端","Balance after":"购买后余额","Battery":"电池","Battery is Full":"电量已满","Battery Status":"电池状态",
"Become a Patron":"成为赞助者","Browse":"浏览","Browse ElevenLabs Voice Library":"浏览 ElevenLabs 语音库","Browse Library":"浏览语音库",
"Build Count":"建造数量","Build games with AI":"用 AI 构建游戏",
"Build your own AI-powered games! Player2 Studio lets you create, test, and share games":"打造你自己的 AI 游戏！Player2 工作室让你创建、测试并分享游戏",
"built in":"内置","Call type":"通话类型","Can't render skin.":"无法渲染皮肤。",
"Character Chat":"角色聊天",
"Character creation is on the Player2 website. Click the button below to start creating your character.":"角色创建在 Player2 官网进行，点击下方按钮开始创建角色。",
"Character editing is now on the Player2 website. Click the button below to edit your character.":"角色编辑已移至 Player2 官网，点击下方按钮编辑角色。",
"Character Voice":"角色语音","Chat Model":"聊天模型","Chat Model dropdown above":"上方聊天模型下拉框","Chat with AISS":"与 AISS 聊天",
"Cheapest first":"最便宜优先","Choose which character voice this will override":"选择要覆盖哪个角色语音",
"Click on the Rewards tab to see various ways to earn free AI Power:":"点击「奖励」标签页，查看各种免费获取 AI 能量的方式：",
"Click to enable":"点击启用","Click to select, play to listen":"点击选择，播放试听",
"Clone Voice":"克隆语音","Clone Voice with Inworld":"使用 Inworld 克隆语音","Clone voices from audio samples using Inworld AI.":"使用 Inworld AI 从音频样本克隆语音。",
"Config":"配置","Configure fallback":"配置回退","Configure speech-to-text settings for voice input.":"配置语音输入的转文字设置。",
"Configure the name and settings for this API profile.":"配置此 API 配置文件的名称与设置。",
"Confirm Deletion":"确认删除","Confirm Patron Purchase":"确认购买赞助","Congratulations!":"恭喜！","Connect":"连接",
"Connect AI coding assistants like Claude Code and Cursor to Player2 tools and resources.":"将 Claude Code、Cursor 等 AI 编程助手连接到 Player2 的工具与资源。",
"Connect your Google or Azure account to earn rewards!":"关联你的 Google 或 Azure 账号以获取奖励！",
"Connected":"已连接","Continue as Guest":"以访客身份继续",
"Controls consistency. Higher values produce more consistent output.":"控制一致性，数值越高输出越一致。",
"Controls expressiveness. Higher values add more emotion and variation.":"控制表现力，数值越高情绪和变化越丰富。",
"Copy code":"复制代码","Copy Code":"复制代码","Copy ID":"复制 ID","Copy URL":"复制链接","Copy User ID":"复制用户 ID","Copy Voice ID":"复制语音 ID",
"Cost":"费用","Create a custom voice from a text description":"根据文字描述创建自定义语音","Create a new Character":"创建新角色",
"Create custom voice instructions that modify how TTS voices sound":"创建自定义语音指令，调整 TTS 语音效果",
"Create custom voices with ElevenLabs Voice Design and Voice Cloning":"通过 ElevenLabs 语音设计与语音克隆创建自定义语音",
"Create ElevenLabs Voice Presets":"创建 ElevenLabs 语音预设","Create Preset":"创建预设","Create Your Character":"创建你的角色",
"Creative":"创意","Creativity":"创造力","Credits per reward":"每项奖励积分","Custom order":"自定义顺序","Custom Server Arguments":"自定义服务器参数",
"Customize individual character voices with ElevenLabs AI voices.":"使用 ElevenLabs AI 语音自定义各个角色的声音。",
"Daily Power Spin":"每日能量转盘","Daily Spin Limit Reached":"已达每日抽奖上限","Date Added":"添加日期","Debug Menu":"调试菜单","Default (auto)":"默认（自动）",
"Delete Log?":"删除日志？","Delete Permanently":"永久删除","Delete profile":"删除配置","Delete Voice":"删除语音","Delete Voice Preset":"删除语音预设",
"Dependency":"依赖项","Describe the issue you're experiencing...":"描述你遇到的问题…",
"Describe your game idea and watch it come to life. Your AI partner writes the code while you see the results in real time.":"描述你的游戏创意，看它变为现实。AI 伙伴负责写代码，你实时看到结果。",
"Description (optional)":"描述（可选）","Design Voice with ElevenLabs":"用 ElevenLabs 设计语音","Developer":"开发者",
"Dismiss":"忽略","Done":"完成","Download":"下载","Download from URL":"从 URL 下载","Download Mod":"下载模组","Download:":"下载：",
"Downloaded custom models:":"已下载的自定义模型：","Downloading from URL...":"正在从 URL 下载…","Downloading update...":"正在下载更新…",
"Dragon's Dogma 2 not found. Click to select the folder.":"未找到《龙之信条 2》，点击选择文件夹。",
"e.g. My Custom Voice":"例如：我的自定义语音","e.g., A warm, friendly female voice with a slight British accent":"例如：温暖友善的女声，略带英国口音",
"Earn Rewards":"获取奖励","Edit settings":"编辑设置","Edit Voice Settings":"编辑语音设置","Edit Your Character":"编辑你的角色",
"ElevenLabs Voice ID":"ElevenLabs 语音 ID","ElevenLabs Voice Mappings":"ElevenLabs 语音映射","ElevenLabs Voice Overrides":"ElevenLabs 语音覆盖","ElevenLabs Voice Presets":"ElevenLabs 语音预设",
"ElevenLabs voice presets are a Patron-only feature. Become a Patron to unlock voice design and voice cloning.":"ElevenLabs 语音预设仅限赞助者使用。成为赞助者即可解锁语音设计与语音克隆。",
"Email:":"邮箱：","Embedding Model":"嵌入模型","Enabled":"已启用"
};
const D = { ...base, ...P };
fs.writeFileSync("i18n/zh-CN.json", JSON.stringify(D, null, 2), "utf8");
console.log("total entries:", Object.keys(D).length);