import fs from "node:fs";
const base = JSON.parse(fs.readFileSync("i18n/zh-CN.json","utf8"));
const P = {
"Enter a direct link to a .gguf model file":"输入 .gguf 模型文件的直链",
"Enter an existing Inworld voice ID to add it to your voice library. Select a system voice that this custom voice will replace.":"输入已有的 Inworld 语音 ID 将其加入语音库，并选择此自定义语音要替换的系统语音。",
"Enter custom instructions for how this voice should speak...":"输入该语音说话方式的自定义指令…",
"Enter text to hear how it sounds with this voice preset...":"输入文本以试听该语音预设的效果…",
"Enter text to test the voice...":"输入文本以测试语音…",
"Error loading search results.":"加载搜索结果出错。",
"Example descriptions:":"描述示例：",
"Factoring in Patron rewards + daily free credits":"已计入赞助者奖励 + 每日免费额度",
"Failed to initialize Studio":"初始化工作室失败",
"Failed to load fallback settings.":"加载回退设置失败。",
"Failed to load voice list. You can still enter voice IDs manually.":"加载语音列表失败，你仍可手动输入语音 ID。",
"Fastest":"最快","Features:":"功能：","Female":"女声","Files":"文件",
"Follow on Instagram":"在 Instagram 关注","Follow on TikTok":"在 TikTok 关注","Free":"免费",
"Game folder:":"游戏文件夹：","Game Location":"游戏位置",
"Game not found. Click to select the installation folder":"未找到游戏，点击选择安装文件夹",
"Game Preview":"游戏预览",
"Games run on AI Power. Be sure to claim your daily free credits.":"游戏运行消耗 AI 能量，记得领取每日免费额度。",
"Gender":"性别","GET CODE":"获取代码","Get Js Free":"免费获取 J","Get Referral Code":"获取推荐码",
"Global image prompt":"全局图像提示词","Global prompt":"全局提示词","Go to Website":"前往官网","Got it":"知道了",
"Here you'll find the supported Player2 games.":"这里列出支持 Player2 的游戏。","History":"历史",
"How closely to match the original voice. Higher values create closer matches.":"与原声的接近程度，数值越高越接近。",
"How it works:":"使用方式：","I understand, install":"我已了解，安装","I understand, install anyway":"我已了解，仍要安装",
"If you already have other mods installed, we cannot guarantee Mantella will work correctly. Conflicts may cause crashes or unexpected behaviour.":"如果你已安装其他模组，我们无法保证 Mantella 正常工作，冲突可能导致崩溃或异常行为。",
"If your selected model is unavailable, these models are tried in order. Pick a preset or drag to arrange your own.":"当所选模型不可用时，将按顺序尝试这些模型。可选择预设或拖动自定义顺序。",
"Image Editing Model":"图像编辑模型","Image Models":"图像模型","Image, Music & Voice Settings":"图像、音乐与语音设置",
"Input Device":"输入设备","Install AISS":"安装 AISS","Install Mantella":"安装 Mantella","Install RiftSpeak":"安装 RiftSpeak",
"Install Warband AI Mod":"安装 Warband AI 模组","Installation complete!":"安装完成！","Installed at:":"安装位置：",
"Installed successfully!":"安装成功！","Installed:":"已安装：","Installer launched!":"安装程序已启动！","Instructions:":"指令：",
"Inworld Voice ID":"Inworld 语音 ID","J's are used to power your AI agents":"J 用于驱动你的 AI 智能体","Jump to last page":"跳至最后一页",
"Keep an eye on your energy levels to ensure your AI agents can keep running!":"留意能量水平，确保 AI 智能体持续运行！",
"Labels (JSON format)":"标签（JSON 格式）","Launch anyway":"仍然启动","Launch Dragon's Dogma 2":"启动《龙之信条 2》",
"Launch Skyrim via SKSE":"通过 SKSE 启动《上古卷轴 5》","Launch through SFSE":"通过 SFSE 启动","Launch Warband (WSE2)":"启动 Warband（WSE2）",
"Leave a Trustpilot review":"在 Trustpilot 留下评价","Let's explore the different sections!":"让我们了解各个板块！",
"Let's take a quick tour to show you around the app!":"快速导览，带你熟悉这个应用！",
"Listen to the generated previews and select your favorite:":"试听生成的预览并选择你喜欢的：",
"Live APIs":"实时 API","Load More":"加载更多","Loading available presets...":"正在加载可用预设…",
"Loading character...":"正在加载角色…","Loading Game...":"正在加载游戏…","Loading voices...":"正在加载语音…",
"Local LLM":"本地 LLM","Local LLM runs entirely on your device.":"本地 LLM 完全在你的设备上运行。",
"Local Models (Free)":"本地模型（免费）","Local Server":"本地服务器","Long (~150 words)":"长（约 150 词）",
"Look to the right side of your screen":"看屏幕右侧","Lowercase letters, numbers, and hyphens only":"仅限小写字母、数字和连字符",
"Main":"主界面","Male":"男声","Manage local models":"管理本地模型","Manage MCP's API Keys":"管理 MCP 的 API 密钥",
"Map ElevenLabs voice IDs to internal Player2 voices. Unmapped IDs use the server default. Voice IDs requested via the API appear automatically.":"将 ElevenLabs 语音 ID 映射到 Player2 内部语音。未映射的 ID 使用服务器默认值，通过 API 请求的语音 ID 会自动出现。",
"Mapped Voice":"已映射语音","Match AI voice language to my input language":"让 AI 语音语言与我的输入语言一致",
"Maybe Later":"稍后再说","MCP key":"MCP 密钥","MCP Server":"MCP 服务器","Medium (~100 words)":"中（约 100 词）",
"Microphone":"麦克风","Mine":"我的","Model Settings":"模型设置","Most capable":"最强",
"Mount & Blade: Warband not found. Click to select the folder.":"未找到《骑马与砍杀：战团》，点击选择文件夹。",
"Move to Trash":"移到回收站","Music":"音乐","Music Model":"音乐模型","My AI Squad":"我的 AI 小队",
"Navigation":"导航","Navigation Tabs":"导航标签页","Neutral":"中性","New":"新建","New Game":"新游戏","Next page":"下一页",
"No approved games found. When you approve games to use the Player2 Web API on your behalf, they will appear here.":"没有已授权的游戏。当你授权游戏代你使用 Player2 Web API 后，它们会显示在这里。",
"No Characters found.":"未找到角色。","No coding experience needed. Just describe your idea and start building.":"无需编程经验，描述你的想法即可开始构建。",
"No custom voices yet. Create one above!":"还没有自定义语音，在上方创建一个吧！",
"No games currently accept log uploads. Game developers must enable this feature for their games.":"目前没有游戏接受日志上传，需要游戏开发者为其启用该功能。",
"No images available":"暂无图片","No leaders to display yet.":"暂无排行榜数据。","No logs uploaded yet.":"尚未上传日志。",
"No models available":"暂无可用模型","No More Schematics!":"没有更多蓝图了！","No other models available for fallback.":"没有其他可用于回退的模型。",
"No presets available. You can download a custom model from URL below.":"暂无预设，你可以从下方 URL 下载自定义模型。",
"No previews available. Please go back and generate previews.":"暂无预览，请返回并生成预览。",
"No project ID provided":"未提供项目 ID","No TTS models available":"暂无 TTS 模型","No Video Available":"暂无视频",
"No voice mappings yet. Voice IDs will appear here automatically when the ElevenLabs-compatible endpoint is used, or you can add them manually below.":"还没有语音映射。使用兼容 ElevenLabs 的接口时语音 ID 会自动出现，也可在下方手动添加。",
"No voice presets found. Create your first preset to get started!":"未找到语音预设，创建你的第一个预设即可开始！",
"No voices found. Try a different search.":"未找到语音，换个关键词试试。",
"Note: Celebrity names cannot be used in voice descriptions.":"注意：语音描述中不能使用名人姓名。",
"One step left, and it happens in the game.":"只剩一步，将在游戏内完成。","Open Config Folder":"打开配置文件夹",
"Open in browser":"在浏览器中打开","Open in Developer Area":"在开发者区域打开","Open in Finder":"在文件管理器中打开",
"Open Presets Folder":"打开预设文件夹","OpenCode Logs":"OpenCode 日志","Opening browser...":"正在打开浏览器…",
"Optional Settings":"可选设置","or click to browse":"或点击浏览","Or type your own answer...":"或输入你自己的回答…",
"Out of AI Power":"AI 能量耗尽","Output Device":"输出设备","Page":"页","Patron":"赞助者","Pay with Card":"用银行卡支付",
"per month":"每月","Play":"开始游戏","Player2 Ad":"Player2 广告","Player2 Studio":"Player2 工作室",
"Please complete the installation using the installer window. Once done, refresh the status to confirm.":"请使用安装程序窗口完成安装，完成后刷新状态以确认。",
"Please log in to chat":"请登录后聊天","Popular":"热门","Power up your gaming experience with AI":"用 AI 为你的游戏体验加速",
"Powered by Sentry":"由 Sentry 提供支持","Precise":"精确","Preset":"预设","Preset downloaded":"预设已下载","Preset name":"预设名称",
"Press Enter to search":"按回车搜索","Private AI Friend":"私密 AI 伙伴","Profile Settings":"个人资料设置","Purchase":"购买",
"Rank":"排名","Recently used":"最近使用","Referral":"推荐","Refresh":"刷新","Remaining Claims":"剩余可领次数","Remote Server":"远程服务器",
"Remove background noise":"去除背景噪音","Remove mapping":"移除映射","Remove Voice Mapping":"移除语音映射","Renewal period":"续费周期",
"Repair":"修复","Repair now":"立即修复","Replace":"替换","Reply":"回复","Required Mods:":"必需模组：","Reset":"重置",
"Reset Guided Tours":"重置新手引导","Reset to system default":"恢复系统默认","Response length":"回复长度","Response Style":"回复风格",
"Response style & global prompt":"回复风格与全局提示词","Responses will be slower":"回复会更慢","Restart":"重启",
"Restarting Studio Agent...":"正在重启工作室代理…","Retry":"重试","Reward Amount":"奖励数量","Rewards":"奖励","Run":"运行","Save":"保存",
"Schematic Type":"蓝图类型","Schematics":"建筑蓝图","Score":"得分","Search":"搜索","Search (Cmd+F)":"搜索（Cmd+F）",
"Search games and mods":"搜索游戏与模组","Search voices":"搜索语音","Select":"选择",
"Select a Player2 voice to replace with your cloned voice":"选择要替换为你克隆语音的 Player2 语音",
"Select a Player2 voice to replace with your custom voice":"选择要替换为你自定义语音的 Player2 语音",
"Select a voice to override":"选择要覆盖的语音","Select a voice to replace...":"选择要替换的语音…","Select a voice...":"选择语音…",
"Select Character":"选择角色",
"Select files for the paths you want to upload. Accepted formats: .log, .txt (max 10MB)":"为要上传的路径选择文件，支持格式：.log、.txt（最大 10MB）",
"Select Game":"选择游戏","Select Player2 voice to replace":"选择要替换的 Player2 语音",
"Select the 3D model provider used for your games.":"选择游戏使用的 3D 模型提供方。",
"Select the embedding model used for your games. Games can request a specific model via the API, which overrides this default for that request.":"选择游戏使用的嵌入模型。游戏可通过 API 请求特定模型，该请求将覆盖此默认设置。",
"Select the Large Language Model (LLM) used":"选择所使用的语言模型（LLM）"
};
const D = { ...base, ...P };
fs.writeFileSync("i18n/zh-CN.json", JSON.stringify(D, null, 2), "utf8");
console.log("total entries:", Object.keys(D).length);