import fs from "node:fs";
const base = JSON.parse(fs.readFileSync("i18n/zh-CN.json","utf8"));
const P = {
"Default":"默认","Leaderboard":"排行榜","Checking installation…":"正在检查安装…","Some components need repair.":"部分组件需要修复。",
"Will install:":"将安装：","Sign in":"登录","Trending":"趋势","Latest":"最新","Language":"语言",
"Subscribe to our YouTube channel":"订阅我们的 YouTube 频道","Total possible credits":"可获得的积分总额","SPIN":"抽取",
"Spin Unavailable":"转盘不可用","Spin Failed":"抽奖失败",
"Something went wrong and no Joules were awarded. Please try again.":"出错了，未获得 J，请重试.",
"Try Again":"重试",
"We allow only 3 accounts per device to earn free Joules daily. If you need more Joules - become a Patron!":"每台设备每天仅限 3 个账号领取免费 J。如需更多 J，请成为赞助者！",
"Studio":"工作室","Settings":"设置","This step may take a few minutes — please wait…":"此步骤可能需要几分钟 —— 请稍候…",
"Your voice input language":"你的语音输入语言","Avatar":"头像","Joules":"J","Thinking Mode":"思考模式","Test voice":"测试语音",
"Voice Design":"语音设计","Voice Clone":"语音克隆","Voice to Replace *":"要替换的语音 *",
"Supports MP3, WAV, M4A formats. Maximum 10 MB per file.":"支持 MP3、WAV、M4A 格式，单个文件最大 10 MB。",
"Your AI Power":"你的 AI 能量","Clear Filters":"清除筛选","Your balance":"你的余额",
"This is a one-off purchase and cannot be undone.":"这是一次性购买，无法撤销。",
"Welcome to your AI Power management! Here you can monitor your energy, earn rewards, and view your usage history.":"欢迎来到 AI 能量管理！在这里你可以查看能量、获取奖励并查看使用记录。",
"Navigation Tabs 📑":"导航标签页 📑","Use these tabs to navigate between different sections:":"使用这些标签在不同板块间切换：",
"Battery Status 🔋":"电池状态 🔋","Earn Rewards 🎁":"获取奖励 🎁","Usage History 📜":"使用记录 📜",
"You're all set! Manage your AI Power efficiently to keep your agents running smoothly.":"一切就绪！合理管理 AI 能量，让智能体流畅运行。",
"Become a Patron 👑":"成为赞助者 👑",
"The easiest way to get more AI Power is to become a Patron! Sign up today!":"获取更多 AI 能量最省事的方式就是成为赞助者！今天就来订阅！",
"You're out of AI Power, but your Daily Spin is available!":"AI 能量耗尽，但你的每日转盘可用！",
"Spin the wheel below for free Joules to continue.":"转动下方转盘免费获取 J 以继续。",
"You're out of AI Power. Get more Joules to continue using AI features.":"AI 能量耗尽，获取更多 J 以继续使用 AI 功能。",
"Join our discord":"加入我们的 Discord","AI STORY":"AI 故事","WEB":"网页","The following will be installed:":"将安装以下内容：",
"Skyrim Special Edition not found. Click to select the folder.":"未找到《上古卷轴 5：特别版》，点击选择文件夹。",
"We strongly recommend a fresh Skyrim installation.":"强烈建议使用干净的上古卷轴 5 安装。",
"The Mantella mod package is ~4 GB. The download may take several minutes.":"Mantella 模组包约 4 GB，下载可能需要几分钟。",
"This step may take several minutes — the package is ~4 GB. Please wait…":"此步骤可能需要几分钟 —— 包约 4 GB，请稍候…",
"We strongly recommend a clean Warband installation.":"强烈建议使用干净的战团安装。",
"The package is ~100 MB. The download may take a few minutes.":"此包约 100 MB，下载可能需要几分钟。",
"We strongly recommend a clean Dragon's Dogma 2 installation.":"强烈建议使用干净的《龙之信条 2》安装。",
"Launching opens the RiftRelay console — leave it open while you play. The Player2 app must be running and signed in.":"启动后会打开 RiftRelay 控制台 —— 游玩期间请保持打开。Player2 应用必须运行并已登录。",
"Starfield folder":"星空文件夹","Your Starfield version cannot run this mod.":"你的《星空》版本无法运行此模组。","Skip":"跳过",
"System default":"系统默认","Loading fallback…":"正在加载回退…","Available to patrons — skipped until you subscribe":"仅赞助者可用 —— 订阅前将跳过",
"Unlimited (default)":"无限制（默认）","Short (~50 words)":"短（约 50 词）",
"Select the Large Language Model (LLM) used for your games.":"选择游戏使用的语言模型（LLM）。",
"Select the model used for image generation.":"选择图像生成使用的模型。","Select the model used for image editing.":"选择图像编辑使用的模型。",
"Upgrade to Patron to use this provider":"升级为赞助者才能使用此提供方","Select the music model used for your games.":"选择游戏使用的音乐模型。",
"Stability":"稳定性","Similarity Boost":"相似度增强","Style":"风格","Speed":"语速","Unassign":"取消分配",
"System Voice to Override":"要覆盖的系统语音","Select the text to speech (TTS) model used for character speech.":"选择角色语音使用的 TTS 模型。",
"Voice presets are a Patron-only feature. Become a Patron to unlock custom voice instructions.":"语音预设仅限赞助者使用。成为赞助者即可解锁自定义语音指令。",
"Voice Instructions":"语音指令","Voice:":"语音：","Video":"视频","Select the video model used for your games.":"选择游戏使用的视频模型。",
"Voice Recognition":"语音识别","Test and debug your API setup":"测试并调试你的 API 配置","Characters":"角色","Loading...":"加载中…",
"Unable to load chat. Please try again.":"无法加载聊天内容，请重试。","Welcome to Player2!":"欢迎来到 Player2！","Player2 Studio 🎮":"Player2 工作室 🎮",
"Build your own AI-powered games! Player2 Studio lets you create, test, and share games — all with the help of AI.":"打造你自己的 AI 游戏！Player2 工作室让你在 AI 帮助下创建、测试并分享游戏。",
"AI Power⚡️":"AI 能量⚡️","AI Settings ⚙️":"AI 设置 ⚙️","Look to the right side of your screen 👉 that's your AI Settings.":"看屏幕右侧 👉 那里是 AI 设置。",
"Navigation 🧭":"导航 🧭","This is your main navigation panel. Here you can access different sections like:":"这是你的主导航面板，可进入以下板块：",
"You will receive":"你将获得","Share & earn 500J per purchase":"分享并在每笔购买中赚取 500J","What you get:":"你将获得：",
"Unable to retrieve user information. Please try again later.":"无法获取用户信息，请稍后重试。",
"You've run out of AI Power to keep building your game. Top up below or upgrade to Patron for more power.":"AI 能量耗尽，无法继续构建游戏。在下方充值或升级为赞助者以获取更多能量。",
"We are processing your PayPal payment. We will let you know once it's ready...":"正在处理你的 PayPal 付款，完成后会通知你…",
"Your subscription will expire soon - if you want to keep all Patron benefits, update your subscription below.":"你的订阅即将到期 —— 如需保留全部赞助者权益，请在下方更新订阅。",
"Username":"用户名","Valid Until":"有效期至","Your Referral Code":"你的推荐码",
"Share this code with your friends to give them a discount on their first subscription:":"把这个码分享给朋友，他们首次订阅可享折扣：",
"Note: Files > 15KB will not have automatic rendered images":"注意：大于 15KB 的文件不会自动生成预览图","Note:":"注意：",
"User Information":"用户信息","User ID:":"用户 ID：",
"These games can access the Web API on your behalf. You can revoke access at any time.":"这些游戏可代你访问 Web API，你可以随时撤销授权。",
"Upload Game Log":"上传游戏日志","Support Logs":"支持日志","Upload game logs to help developers troubleshoot issues.":"上传游戏日志，帮助开发者排查问题。",
"Upload Log":"上传日志","File":"文件","Size":"大小","Uploaded":"已上传",
"Voice mappings unavailable. The Developer API may still be starting up.":"语音映射不可用，开发者 API 可能仍在启动中。",
"Setting up required tools...":"正在准备所需工具…","What do you want to build?":"你想构建什么？","Trash":"回收站","Trash is empty":"回收站是空的",
"Starting preview server...":"正在启动预览服务器…","Studio Agent Stopped":"工作室代理已停止","The Studio Agent process has stopped unexpectedly.":"工作室代理进程意外停止。",
"Starting Player2 Studio Agent...":"正在启动 Player2 工作室代理…","What would you like to build?":"你想构建什么？","Stop generating":"停止生成",
"Starting Studio...":"正在启动工作室…","Checking tools...":"正在检查工具…","Waiting for data...":"正在等待数据…","Server Logs":"服务器日志",
"Something went wrong":"出了点问题","Try refreshing the page":"请尝试刷新页面","Update Failed":"更新失败","Your app is out of date":"你的应用已过期",
"Welcome to Player2":"欢迎来到 Player2","Sign in with Player2":"使用 Player2 登录","Games🕹️":"游戏🕹️",
"Afrikaans":"南非荷兰语","Armenian":"亚美尼亚语","Assamese":"阿萨姆语","Azerbaijani":"阿塞拜疆语","Cebuano":"宿务语","Chichewa":"齐切瓦语",
"Chinese":"中文","Filipino":"菲律宾语","Galician":"加利西亚语","Georgian":"格鲁吉亚语","Gujarati":"古吉拉特语","Hausa":"豪萨语",
"Icelandic":"冰岛语","Irish":"爱尔兰语","Javanese":"爪哇语","Kazakh":"哈萨克语","Kirghiz":"吉尔吉斯语","Lingala":"林加拉语",
"Luxembourgish":"卢森堡语","Malayalam":"马拉雅拉姆语"
};
const D = { ...base, ...P };
fs.writeFileSync("i18n/zh-CN.json", JSON.stringify(D, null, 2), "utf8");
console.log("total entries:", Object.keys(D).length);